POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "unite",
  "details": "um evento incrivel",
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/1ecbf2d6-c0fd-4b42-8f0e-4bc068dabb6a/attendees
Content-Type: application/json

{
  "name": "kazuo4",
  "email": "otaviokazuo4@hotmail.com"
}